config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :users do
   resources :products do
    resources :orders
   end
  end
  # resources :products
  
  # get 'dashboard', to: 'users#dashboard'
  # resources :dashboard
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  
  has_many :order
end

app/models/user.rb
class User < ApplicationRecord
    has_many :product,dependent: :destroy
  
    has_one :user_profile
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

    def index
        @sho = User.all
        
    end

    def show
        # @explain = User.find(params[:id])
        # @orders = @explain.order.includes(:product) 


        @user=User.find(params[:id])
        @orders=@user.order

        # @orders=Order.find(params[:id])
        # user = @orders.user
        # user_id= user.id
    end
    

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 
  def index
    @orders = Order.all
  end

  def show
    # @order= Order.find_by(params[:user_id])
    # @order= Order.find(params[:id])
   
    # @order = Order.all.includes(:product)
      @user=User.find(params[:id])

      # @order=Order.find_by(user_id: @user.id)
     @product=Product.where('user_id=?',@user.id)
  end

    
    # def new
    #     @user=Product.find(params[:id])
    #     @orders=@user.order.new
    # end

    #       @products = Product.all.includes(:user)
      
    #         @product = Product.find(params[:order_product_id])
    #         @order = Order.new(user: current_user, product: @product) # Assuming you have a current_user method
      

    # before_action :set_product

    def create
      @order = Order.new(user: current_user, product: @product)
  
      if @order.save
        redirect_to dashboard_path, notice: 'Order was successfully created.'
      else
        redirect_to dashboard_path, alert: 'Failed to create order.'
      end
    end
  
    private
  
    def show_ord
      params.require(:order).permit(:user_id, product_id)
    end


    def set_product
      @product = Product.find(params[:product_id])
    end
  

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


    
    def index
        @sho = Product.all
        @order = Order.new
    end

    def new
        @explain = User.find(params[:user_id])
        @gro = Product.new
    end

    def show
        @explain = Product.find(params[:id])
    end

    def edit
        @detec = Product.find(params[:id])
    end

    def create
        @explain = User.find(params[:user_id])
        @photosynthesis =  @explain.product.new(product_params)
        if @photosynthesis.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def update
        @run =  Product.find(params[:id])
        if @run.update(product_params)
            redirect_to @run
        else
            render 'edit'
        end
    end

        def destroy
            @aloo = Product.find(params[:id])
            @aloo.destroy
            redirect_to user_path
        end

        def product_params
            params.require(:product).permit(:product_name, :user_id)
        end
           

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def dashboard
    
    end


    def index
        @sho = User.all
        @gro = Product.new
    end

    def new
        @grow = User.new
    end

    def show
        @explain = User.find(params[:id])
    end

    def edit
        @detect = User.find(params[:id])
    end

    def create
        @photosynthesis = User.new(user_params)
        if @photosynthesis.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def update
        @run =  User.find(params[:id])
        if @run.update(user_params)
            redirect_to @run
        else
            render 'edit'
        end
    end

        def destroy
            @aloo = User.find(params[:id])
            @aloo.destroy
            redirect_to users_path
        end

        def user_params
            params.require(:user).permit(:name, :email, :phno)
        end
            
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<h1>DASHBOARD</h1>

<style type="text/css">
table, th, td{
    text-align:center;
  border: 1px solid ;
}
</style>


<p> <%=link_to "register", new_user_path %> </p>

<table class="table">
  <thead class="thead-dark">
    <tr>
    <th scope="col">id</th>
    <th scope="col">name</th>
    <th scope="col">show order</th>
    <th scope="col">all product</th>
        </tr>
    </thead>
    <tbody>
    <% @sho.each do |table| %>
        <tr>
        <td> <%=table.id %> </td>
        <td> <%=table.name %> </td>
        <td> <%= link_to "show order", order_path(table.id) %> </td>
        <td> <%=link_to "all product", user_products_path(table.id)	 %> </td>
        <% end %>
        </tr>
    </tbody>

    </table>

app/views/dashboard/new.html.erb
<div>
<%= form_with model: [@explain, @gro] do |form| %>
    <div>
      <%= form.label :product_name %><br>
      <%= form.text_field :product_name %>
     </div>

     <div>
     <%= form.label :user_id %><br>
     <%= form.text_area :user_id %>
     </div>

     
     <div>
        <%= form.submit %>
     </div>

<% end %>
</div>

app/views/dashboard/show.html.erb
<h3>Orders</h3>
  <ul>
    <% @orders.each do |order| %>
      <li>
        Product: <%= order.product.product_name %>
      </li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YourAppName</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/orders/index.html.erb
<style type="text/css">
table, th, td{
    text-align:center;
  border: 1px solid ;
}
</style>




<h1>ALL orders </h1>

<p> <%=link_to "new user", new_order_path %> </p>

<table>
    <thead>
        <tr>
        <td>id</td>
        <td>u</td>
        <td>p</td>
        <td></td>
        <td>change</td>
        <td>destro</td>
        <td>add product</td>
        <td>show product</td>
        </tr>
    </thead>
    <tbody>
    <% @orders.each do |table| %>
        <tr>
        <td> <%=table.id %> </td>
        <td> <%=table.user_id %> </td>
        <td> <%=table.product_id %> </td>
       
        <td>  </td>
        <td> <%=link_to "edit" ,edit_user_path(table.id) %> </td>
        <td> <%=link_to "delete", user_path(table.id), data: {turbo_method: :delete,turbo_confirm: "Are you sure?" } %> </td>
        <td> <%=link_to "add product", new_user_product_path(table.id) %> </td>
        <td> <%=link_to "show product", user_path(table.id) %> </td>
        <% end %>
        </tr>
    </tbody>

app/views/orders/show.html.erb
<h3>Orders</h3>
 
  <ul>
    <% @product.each do |product|   %>
        <li>
        <%=product.product_name%>
        </li>
                
    <% end %>
  
  
  

app/views/products/_form.html.erb
<div>
<%= form_with model: forme do |form| %>
    <div>
      <%= form.label :product_name %><br>
      <%= form.text_field :product_name %>
     </div>

     <div>
     <%= form.label :user_id %><br>
     <%= form.text_area :user_id %>
     </div>

     
     <div>
        <%= form.submit %>
     </div>

<% end %>
</div>

app/views/products/edit.html.erb
<h1>EDIT PRODUCTS</h1>


<%= render "form", forme: @detec %>

app/views/products/index.html.erb
<style type="text/css">
table, th, td{
    text-align:center;
  border: 1px solid ;
}
</style>




<h1>ALL PRODUCTS </h1>


<table>
    <thead>
        <tr>
        <td>id</td>
        <td>name</td>
        <td>user_id</td>
        <td></td>
        <td>order</td>
        </tr>
    </thead>
    <tbody>
    <% @sho.each do |table| %>
        <tr>
        <td> <%=table.id %> </td>
        <td> <%=table.product_name %> </td>
        <td> <%=table.user_id %> </td>
        <td>  </td>
        <td> <%=link_to "add order", new_user_product_order_path(table.id,table.user_id) %> </td>
     
          
    
       <% end %>
        </tr>
    </tbody>

app/views/products/new.html.erb
<style type="text/css">
form { 
margin: 0 auto; 
width:250px;
text-align: center;
}
</style>


<h1>NEW PRODUCTS</h1>

<%= render "form", forme: [@explain, @gro]%>

app/views/products/show.html.erb
<h1><strong><%= @explain.id%></strong></h1>
<h1><strong><%= @explain.product_name%></strong></h1>
<p> </p>

app/views/users/_form.html.erb
<%= form_with model: forme , html: { class: 'bg-light p-4 rounded shadow' } do |form| %>
  <div class="form-group mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Enter your name' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control', placeholder: 'Enter your email' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :phno, class: 'form-label' %>
    <%= form.number_field :phno, class: 'form-control', placeholder: 'Enter your phone number' %>
  </div>

  <div class="d-flex justify-content-between">
    <%= form.submit 'Create User', class: 'btn btn-primary' %>
    <%= link_to 'Cancel', users_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<h1>DASHBOARD</h1>

app/views/users/edit.html.erb
<h1>EDIT USERS</h1>


<%= render "form", forme: @detect %>

app/views/users/index.html.erb
<style type="text/css">
table, th, td{
    text-align:center;
  border: 1px solid ;
}
</style>




<h1>ALL USERS </h1>

<p> <%=link_to "new user", new_user_path %> </p>

<table>
    <thead>
        <tr>
        <td>id</td>
        <td>name</td>
        <td>email</td>
        <td>phno</td>
        <td></td>
        <td>change</td>
        <td>destro</td>
        <td>add product</td>
        <td>show product</td>
        </tr>
    </thead>
    <tbody>
    <% @sho.each do |table| %>
        <tr>
        <td> <%=table.id %> </td>
        <td> <%=table.name %> </td>
        <td> <%=table.email %> </td>
        <td> <%=table.phno %> </td>
        <td>  </td>
        <td> <%=link_to "edit" ,edit_user_path(table.id) %> </td>
        <td> <%=link_to "delete", user_path(table.id), data: {turbo_method: :delete,turbo_confirm: "Are you sure?" } %> </td>
        <td> <%=link_to "add product", new_user_product_path(table.id) %> </td>
        <td> <%=link_to "show product", user_path(table.id) %> </td>
        <% end %>
        </tr>
    </tbody>

app/views/users/new.html.erb
<style type="text/css">
form { 
margin: 0 auto; 
width:250px;
text-align: center;
}
</style>


<h1>REGISTRATION</h1>


<%= render "form", forme: @grow %>

app/views/users/show.html.erb
<h1>id:<%= @explain.id%></strong></h1>
<h1>name:<%= @explain.name%></strong></h1>
<h1>phno:<%= @explain.phno%></strong></h1>
<p> </p>







<style type="text/css">
table, th, td{
  border: 1px solid ;
}
</style>
<div>
<table style="width: 100%">
<% @explain.product.each do |info| %>

    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th> </th>
        </tr>
    </thead>
    <tbody>
        <tr>
        <td><%= info.id %></td>
        <td><%= info.product_name %></td>
        <td><%#= link_to "huu", product_path(info.id) ,  data: {turbo_method: :delete,turbo_confirm: "Are you sure?" } %> </td>
        </tr>
    </tbody>
    <% end %>
</table>

</div>


 <%= link_to 'Back to square one', root_path %>